### ISSUE TITLE
DNSFORWARDER issue

### ISSUE THREAD

**Issue by tbs575** [Fmstrat/samba-domain#11]
1. I used docker startup this image with DNSFORWARDER=10.193.10.1, 
2. set /etc/resolv.conf content with nameserver 10.193.10.204 (docker host ip) on other client. 
3. but I can not ping www.bing.com
error:
[root@localhost god]# ping www.bing.com
ping: www.bing.com: Name or service not known
4. using nslookup checking.
[root@localhost god]# nslookup www.bing.com 10.193.10.1
Server:         10.193.10.1
Address:        10.193.10.1#53

Non-authoritative answer:
www.bing.com    canonical name = a-0001.a-afdentry.net.trafficmanager.net.
a-0001.a-afdentry.net.trafficmanager.net        canonical name = cn.cn-0001.cn-msedge.net.
cn.cn-0001.cn-msedge.net        canonical name = cn-0001.cn-msedge.net.
Name:   cn-0001.cn-msedge.net
Address: 202.89.233.100
Name:   cn-0001.cn-msedge.net
Address: 202.89.233.101

it seemed it is not working with DNSFORWARDER=10.193.10.1. how can I do?

**Comment by antonioj-mattos** [comment]
Hi @tbs575 

I've had a similar problem, then looking at the config file at `/var/lib/samba/config/samba/` I noticed the setting was being overridden at some point 

```sh
[global]
        dns forwarder = 10.109.50.22
        idmap_ldb:use rfc2307 = yes
                        wins support = yes
 
        server role = active directory domain controller
        dns forwarder = 127.0.0.11  # <--- redefinition
```

It worked after I comment out the second definition.

**Comment by bobweaddabbitsaboi** [comment]
> Hi @tbs575
> 
> I've had a similar problem, then looking at the config file at `/var/lib/samba/config/samba/` I noticed the setting was being overridden at some point
> 
> ```shell
> [global]
>         dns forwarder = 10.109.50.22
>         idmap_ldb:use rfc2307 = yes
>                         wins support = yes
>  
>         server role = active directory domain controller
>         dns forwarder = 127.0.0.11  # <--- redefinition
> ```
> 
> It worked after I comment out the second definition.

Had the same issue but in /etc/smb.conf

**Comment by Fmstrat** [comment]
@meatsac @tbs575 Are either of you using an external config? Can you send in your compose file? I think this may be related to the `cp` issue, or it's getting replaced on provision.

**Comment by sasa-friedrich-bitlab** [comment]
I can confirm same thing (dns forwarder written twice). Here is my docker-compose.yml:

```
version: '2'

networks:
  samba-pdc:
    external: true

services:

  samba:
    image: samba-domain:latest
    container_name: samba-dc
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/:/var/lib/samba
      - ./config/:/etc/samba/external
    environment:
      - DOMAIN=TEST.LOCAL
      - NOCOMPLEXITY=true
      - DOMAINPASS=test123
      - DNSFORWARDER=8.8.8.8
      - HOSTIP=192.168.100.2
    networks:
      - samba-pdc
    ports:
      - 192.168.100.2:53:53
      - 192.168.100.2:53:53/udp
      - 192.168.100.2:88:88
      - 192.168.100.2:88:88/udp
      - 192.168.100.2:135:135
      - 192.168.100.2:137-138:137-138/udp
      - 192.168.100.2:139:139
      - 192.168.100.2:389:389
      - 192.168.100.2:389:389/udp
      - 192.168.100.2:445:445
      - 192.168.100.2:464:464
      - 192.168.100.2:464:464/udp
      - 192.168.100.2:636:636
      - 192.168.100.2:1024-1044:1024-1044
      - 192.168.100.2:3268-3269:3268-3269
    dns_search:
      - test.local
    dns:
      - 192.168.100.2
      - 192.168.100.1
    extra_hosts:
      - dc.test.local:192.168.100.2
    hostname: dc
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    privileged: true
    restart: always
```
