### ISSUE TITLE
ERROR(runtime): uncaught exception - DsAddEntry failed

### ISSUE THREAD

**Issue by belqit** [Fmstrat/samba-domain#17]
```
version: '2'
networks:
  extnet:
    external: true
services:
  samba:
    build: ./
    container_name: samba
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/test/storage:/storage
      - /root/test/config:/etc/samba/external
    environment:
      - DOMAIN=B**A.LOCAL
      - DOMAINPASS=********
      - JOIN=true
      - DNSFORWARDER=192.168.0.32
      - HOSTIP=192.168.0.187
    networks:
      - extnet
    ports:
      - 192.168.0.187:53:53
      - 192.168.0.187:53:53/udp
      - 192.168.0.187:88:88
      - 192.168.0.187:88:88/udp
      - 192.168.0.187:135:135
      - 192.168.0.187:137-138:137-138/udp
      - 192.168.0.187:139:139
      - 192.168.0.187:389:389
      - 192.168.0.187:389:389/udp
      - 192.168.0.187:445:445
      - 192.168.0.187:464:464
      - 192.168.0.187:464:464/udp
      - 192.168.0.187:636:636
      - 192.168.0.187:1024-1044:1024-1044
      - 192.168.0.187:3268-3269:3268-3269
    dns_search:
      - B**A.LOCAL
    dns:
      - 192.168.0.187
      - 192.168.0.32
    extra_hosts:
      - localdc.b**a.local:192.168.0.187
      - b**a.local:192.168.0.32
    hostname: localdc
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    privileged: true
    restart: always

```

![image](https://user-images.githubusercontent.com/44238749/72175159-5b3c0e80-33d3-11ea-8b23-57994fdcefd4.png)

I'm using another user instead of administrator
