### ISSUE TITLE
Log files not created

### ISSUE THREAD

**Issue by mkonars** [Fmstrat/samba-domain#5]
Hi, I have problem with creating the log files. Here is my configuration.

log file = /var/log/samba.log
log level = 10 auth:5 winbind:5
debug level = 10
syslog = 10

Any help appreciated.

**Comment by Fmstrat** [comment]
What is your docker/compose setup?

**Comment by diegolabonia** [comment]
Hi, I'm having the same issue here.

**docker-compose.yml**
```
version: '2'
services:
  samba:
    image: myrepo/samba:latest
    container_name: samba
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/var/lib/samba
      - ./config:/etc/samba/external
      - /storage/:/storage
      - /storage/logs/samba:/logs
    environment:
      - DOMAIN=mydomain.local
      - DNSFORWARDER=8.8.8.8
      - HOSTIP=x.x.x.x
      - DOMAINUSER=myuser
      - DONAINPASSWORD=mypassword
    ports:
      - 53:53
      - 53:53/udp
      - 88:88
      - 88:88/udp
      - 135:135
      - 137-138:137-138/udp
      - 139:139
      - 389:389
      - 389:389/udp
      - 445:445
      - 464:464
      - 464:464/udp
      - 636:636
      - 1024-1044:1024-1044
      - 3268-3269:3268-3269
    dns_search:
      - mydomain.local
    dns:
      - 127.0.0.1
      - 8.8.8.8
    extra_hosts:
      - ad.mydomain.local:x.x.x.x
    hostname: ad
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    privileged: true
    restart: always
```

**smb.conf**
```
[global]
    log level = 2 auth:5 winbind:5 auth_audit:3
    log file = /logs/samba.log
    max log size = 2048
    syslog only = no
    syslog = 3
    dns forwarder = 8.8.8.8
    idmap_ldb:use rfc2307 = yes
    wins support = yes
    template shell = /bin/bash
    winbind nss info = rfc2307
    idmap config MYDOMAIN: range = 10000-20000
    idmap config MYDOMAIN: backend = ad
    workgroup = MYDOMAIN
    realm = MYDOMAIN.LOCAL
    netbios name = AD
    server role = active directory domain controller
    dns forwarder = 127.0.0.11
    idmap_ldb:use rfc2307 = yes
    # For icinga2 web authentication
    ldap server require strong auth = no
```

/logs is a mounted volume, in which samba creates the following structure:
.
└── cores
    └── winbindd

In /var/log/samba it generates:
.
|-- cores
|   |-- smbd
|   `-- winbindd
`-- log.smbd (always empty)

I've also installed syslog on the container and samba isn'l logging there either.

Any ideas?
